### ISSUE TITLE
README incorrect - "latter" should be "former"

### ISSUE THREAD

**Issue by mglanville** [cemerick/jsdifflib#19]
The [Python Interoperability](https://github.com/cemerick/jsdifflib#python-interoperability) section says:

> So, you have the choice of doing everything in Javascript on the browser, or falling back to server-side diff...

and then goes on to say:

> Most of the time, we do the latter, simply because while jsdifflib is pretty fast all by itself, and is totally usable for diffing "normal" files....

This doesn't make sense. "latter" in that second quote should be "former".

**Comment by jaden** [comment]
The readme is correct as written. It's saying they usually use server-side diffing.

Former: In-browser diffing
Latter: Server-side diffing

If it was changed to former, then it would be saying most of the time they use in-browser diffing. But that's not true, because:

> [W]e regularly need to diff files that are 1 or 2 orders of magnitude larger than that. For that, server-side diffing is a necessity.

**Comment by mglanville** [comment]
Aha... I see. Thanks for the explanation.
