### ISSUE TITLE
WHY THE FOLLOWING CODEING COULDN'T PASS THE EXAM ON https://oj.bnuz.edu.cn/problemset/7/problem/592,BUT OK ON dev c++

### ISSUE THREAD

**Issue by echo1007** [cemerick/jsdifflib#27]
WHAT IS WRONG?  I KNOW THE PROGRAM IS FROM HERE, SO I MUST GET THE ANSWER FROM HERE. THIS KIND OF THING IS ALWAYS HAPPENED ON ME.

#include<stdio.h>
int main(){
	int n;
	scanf("%d",&n);
	for(int i = 1;i <= n+1;i ++){
		for(int j = 1;j <=2 * n+1;j ++){
			if(j == n + i || j == n -i + 2){
				printf("*");
			}
			else{
				printf(".");
			}
		}
		printf("\n"); 
	}
	for(int i = n;i >= 1;i --){
		for(int j = 2 * n+1;j >=1;j--){
			if(j == n + i || j == n -i + 2){
				printf("*");
			}
			else{
				printf(".");
			}
		}
		printf("\n"); 
	}
}

**Comment by purplesyringa** [comment]
WHY DO YOU THINK THIS PROGRAM IS FROM HERE?

P.S. SORRY FOR CAPSLOCK
