### ISSUE TITLE
does this works on nodejs or rhino ? 

### ISSUE THREAD

**Issue by cancerberoSgx** [cemerick/jsdifflib#8]

**Comment by jzabroski** [comment]
@cancerberoSgx  Can you be more specific?  How would it work on nodejs?

**Comment by VMBindraban** [comment]
For future reference: https://github.com/marcosc90/node-jsdifflib

**Comment by cancerberoSgx** [comment]
This is a very od issue, I don't remember what were my thoughts then - closing it - sorry for the noise. thanks
